In [4]:
for i in range(100):
   if i==50:
       print(i)
       continue
   else:
       print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [6]:
for i in range(100):
   if i==50:
       print(i)
       break
   else:
       print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


<!-- 7th August Labs -->


In [ ]:
# 7th AUgust Labs



In [15]:
def display_message(top,set):
    print(f"today's Topic is(top)")
    print(f"{set}")
    
display_message("function","Today we learnt about python")
    

today's Topic is(top)
Today we learnt about python


In [41]:
def fav_book(fvrt):
    print(f"my favourite book is {fvrt} Written By Napoleon Hill")
fav_book("(Think and Grow Rich)")


my favourite book is (Think and Grow Rich) Written By Napoleon Hill


In [37]:
def describe_cars(name , model):
    print(f"i have a {name} of {model} model")
    print(f" {model} model")
describe_cars("farari", "2001")

i have a farari of 2001 model


In [82]:
x = int(input("size of your shirt:"))
def make_shrt(size):
    if size <=12:
        print(f"your shirt size is small and your size {size} ")
    elif size <=15:
        print(f"your shirt size is medium and your size{size} ")
    elif size <=20:
        print(f"your shirt size is large and your size{size} ")
    else:
        print(f" your shirt size is extra large and your size:{size}   \n") 
   
  
    return size
make_shrt(x)


size of your shirt: 44


 your shirt size is extra large and your size:44   



44

In [3]:
# 8 August Labs


In [7]:
 # import only sin and pi from maths module:
from math import sin,pi
print (math.sin(3.14))
print(pi) 

0.0015926529164868282
3.141592653589793


In [15]:
from math import sin,pi
print(math.sin(90))
print(sin)

0.8939966636005579
<built-in function sin>


In [3]:
import math
math.ceil(3.14)

4

In [25]:
import random
random.randint(1,20)


18

In [27]:
import random
random.uniform(1,20)

4.869995347694625

In [31]:
random.choice([1,"up","down",2,3,5,6])

3

In [34]:
import math
8**2

64

In [49]:
math.pow(4,3)     

64.0

In [53]:
53==106/2

True

In [55]:
53==104/2

False

In [57]:
math.pi

3.141592653589793

In [59]:
  math.sqrt(math.pi)       #formula for square root

1.7724538509055159

In [63]:
math.dist([3],[6])         #formula for distance

3.0

In [65]:
math.dist([-3],[-6])  #arrangement dosen't matter, we can change sequence like we can write -6 first

3.0

In [67]:
math.ceil(3.14157)

4

In [1]:
# 12th august labs
#Class


In [1]:
class BankAccount:
.    def __init__(self, owner, balance=0):
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        print("Amount Deposited: ", amount)
        self.balance += amount
        print("Total Balance: ", self.balance)

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient Balance")
        else:
            self.balance = self.balance - amount
            print(f"{amount} is withdrawn")

    def get_balance(self):
        return self.balance
obj1 = BankAccount("ABC", 1300)
obj1.deposit(9000)
print("Current Balance: ", obj1.get_balance())
obj1.withdraw(5000)
print("Current Balance: ", obj1.get_balance())


Amount Deposited:  9000
Total Balance:  10300
Current Balance:  10300
5000 is withdrawn
Current Balance:  5300


In [ ]:

# Python Class Example: Managing Employee Information with Methods for Full Name, Email, Salary, and Department


In [1]:
class employInformation():
    def __init__(self,fname,sname,salary,department):
        self.fname=fname
        self.sname=sname
        self.salary=salary
        self.department=department
    def fullName(self):
        print(f'Full name: {self.fname+" "+self.sname}')
    def email(self):
        print(f'Email: {self.fname+self.sname+"0786@gmail.com"}')
    def employ_department(self):
        print(f'Department: {self.department}')
    def employ_salary(self):
        print(f'Salary:',self.salary)
obj=employInformation('Waseem','waso',30000,' Management')
obj.fullName()
obj.email()
obj.employ_salary()
obj.employ_department()

Full name: Waseem waso
Email: Waseemwaso0786@gmail.com
Salary: 30000
Department:  Management


In [4]:
list = [1 , 4 ,5]
list2 = [2 , 5 ,6]
list4 = list[2] + list[0]
list4

6

In [20]:
import numpy as np
list = np.array([2 , 5 ,6 ,66 , 65 , 76])
index = np.array([2 , 3])
list_4 = np.arange(8)
list_5= np.shape(list)
list[index]
list_5

(6,)

In [20]:
import numpy as np
list = np.array([2 , 5 ,6 ,66 , 65 , 76])
index = np.array([2 , 3])
list_4 = np.arange(8)
list_5= np.shape(list)
list[index]
list_5

(6,)

In [20]:
import numpy as np
list = np.array([2 , 5 ,6 ,66 , 65 , 76])
index = np.array([2 , 3])
list_4 = np.arange(8)
list_5= np.shape(list)
list[index]
list_5

(6,)

In [17]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.ones((2 , 3 ,3, 4))
print(d)


[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [21]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.ones((2 , 3 ,3, 4))
d.ndim



4

In [23]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.ones((2 , 3 ,3, 4))
d.size


72

In [25]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.ones((2 , 3 ,3))
d.ndim


3

In [27]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((2 , 3 ,3, 4))
print(d) 


[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [29]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((2 , 3 ,3, 4))
d.size


72

In [31]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((2 , 3 ,3, 4))
d.ndim


4

In [1]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((2 , 3 ,3, 4))
d.ndim
d


array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [35]:
import numpy as np

# Create a 3x3 matrix with all elements as 1
d = np.zeros((10,50,10))
print(d)


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [2]:
             ##Taking Input in Python
#DECIMAL NUMBER

num = int(input("Enter a number: "))
print(num, " ", type(num))
floatNum = float(input("Enter a decimal number: "))
print(floatNum, " ", type(floatNum))

#SUM OF TWO NUMBER 

num1 =int(input("enter a number:"))
num2 =int(input("enter a  second number:"))
a=num1+num2
print("the sum of two number:",a)

# PRODUCT OD TWO NUMBER

num1 =int(input("enter a number:"))
num2 =int(input("enter a  second number:"))
a=num1*num2
print("the product of two number:",a)

## QUENTIENT OF TWO NUMBWER

num1 =int(input("enter a number:"))
num2 =int(input("enter a  second number:"))
a=num1//num2
print("the  quentient of two number:",a)

##DIFFERENCE OF TWO NUMBER

num1 =int(input("enter a number:"))
num2 =int(input("enter a  second number:"))
a=num1-num2
print("the difference two number:",a)

## MODULUS OF TWO NUMBER

num1 =int(input("enter a number:"))
num2 =int(input("enter a  second number:"))
a=num1%num2
print("the  modulus of two number:",a)



Enter a number:  12


12   <class 'int'>


Enter a decimal number:  12


12.0   <class 'float'>


enter a number: 12
enter a  second number: 12


the sum of two number: 24


enter a number: 12
enter a  second number: 45


the product of two number: 540


enter a number: 98
enter a  second number: 45


the  quentient of two number: 2


enter a number: 34
enter a  second number: 34


the difference two number: 0


enter a number: 67
enter a  second number: 46


the  modulus of two number: 21


In [3]:
##●	Write a program that asks the user to enter two numbers, obtains the two numbers from the user and prints the sum, product, difference, quotient and remainder of the two numbers. Sample output is as following:

radius = int(input("enter a number"))
print("the diameter is:",2*radius)
print("the circumference is;",2*3.14159*radius)
print("the area is:",3.14159*radius**2)


enter a number 9


the diameter is: 18
the circumference is; 56.54862
the area is: 254.46878999999998


In [4]:
#●	Write a program that produces the following output using variables instead of hardcoding:
#HHHHHH
   #HHHHH
        # HHH
           # HH
               #H

print('HHHHHH')
print('HHHHH')
print('HHH')
print('HH')
print('H')

HHHHHH
HHHHH
HHH
HH
H


In [5]:
#Write a program that reads an integer and determines and prints whether it is odd or even.
number = int(input("enter number: "))
if number%2:
     print(number,"is an odd number.")
            
else:
    print(number,"is an even number.")
  
            

enter number:  45


45 is an odd number.


In [6]:
#Write a program that reads an integer and determines and prints whether it is odd or even.
number = int(input("enter number: "))
if number%2:
     print(number,"is an odd number.")
            
else:
    print(number,"is an even number.")
  
            

enter number:  22


22 is an even number.


In [7]:
##●	Create a variable x that stores an integer. Print out x, 2x, 3x, 4x, and 5x, each separated by three dashes, like below if x=7. (hint: use multiplication operator and print function)
                                        ##7---14---21---28---35	
x=7
print(f"{x}---{2*x}---{3*x}---{4*x}---{5*x}")


7---14---21---28---35


In [8]:
degree_celsius=26.0
f= 9/5*degree_celsius+32
print(f)

degree_celsius=0.0
f=9/5*degree_celsius+32
print(f)

difference =20
double=2*difference
print(double)

78.80000000000001
32.0
40


In [9]:
     ## VARIABLE
# FIND AREA
length=22.0
width=5.0
area=length*width
print(area)


110.0


In [10]:

                ## ARITHMETIC OPERATION
##●	For each of the following expressions, what value will the expression give? Verify your answers by typing the expressions into Python.##
# for addition
a =9
b= 3
c=a-b;
print(c)
#for multiplaction
a=8
b=2.5
c=a*b;
print(c)
#for integer division
a=9
b=2
c=a/b;
print(c)

a=9
b=-2
c=a//b
print(c)
#for modulus
a=9
b=2
c=a%b;
print(c)
#
a=9.0
b=2
c=a%b
print(c)
a=9
b=2.0
c=a%b
print(c)
a=9
b=-2
c=a%b
print(c)
a=-9
b=2
c=a%b
print(c)
a=9
b=-2.0
c=a%b
print(c)
a=4
b=3
c=5
d=a+b*c
print(d)
a=4
b=3
c=5
d=(a+b)*c
print(d)

6
20.0
4.5
-5
1
1.0
1.0
-1
1
-1.0
19
35


In [12]:
#1.	Write a program in jupyter notebook, that prints on screen the message Hello, World.
print("hello world")

hello world


In [16]:
#    Using the program in (1), what happens if we remove the closing quotation around the text Hello, World?
print("hello world)

SyntaxError: unterminated string literal (detected at line 2) (207287347.py, line 2)

In [17]:
#$	Using the program in (1), what happens if we remove both the quotations around the text Hello, World? How is it different from the behavior in (2)
print(hell world)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1985553770.py, line 2)

In [18]:
#4.	Write a program using the print() command  that produces the following output:
print("*")
print("**")
print("*** ")
print("**** ")
print("***** ")

*
**
*** 
**** 
***** 


In [19]:
def addition_1(num1,num2):
    return num1+num2

In [20]:
addition_1(1,2)

3

In [21]:
#defining classqand its structure
class Account_1():
    owner="abdul"
    balance=5000

In [22]:
#initilizing my Account
my_acc= Account_1()

In [24]:
print(my_acc.owner)
print(my_acc.balance)

abdul
5000


In [25]:
#nested    for loop
for i in range(0,5):
    print("outer loop")
for j in range(0,2):
    print("inner loop")

outer loop
outer loop
outer loop
outer loop
outer loop
inner loop
inner loop


In [26]:
#if statment
if 5>3:
    print("5 is greater then 3")
    if 2>1:
        print("2 is greater then 1")

5 is greater then 3
2 is greater then 1


In [27]:
#list in list  two diamensional array
list_variable=[1,'a',3.14, "True"]
list_variable=[1,['a','b','c'],'a',3.14,"True"]
list_variable[1][:]

['a', 'b', 'c']

In [28]:
   list_variable=[1,'a',3.14, "True"]
list_variable=[1,['a','b','c'],'a',3.14,['b1','b2','b3']]
list_variable[4][:]

['b1', 'b2', 'b3']

In [29]:
 list_variable=[1,'a',3.14, "True"]
list_variable=[1,['a','b','c'],'a',3.14,['b1','b2','b3']]
list_variable[4][-2] # negative index

'b2'

In [30]:
class book:
    name ="phythn"
    price=202
    author="pata nae"
    page=400
bookone=book()
print(bookone.name)
print(bookone.price)
print(bookone.author)
print(bookone.page)

phythn
202
pata nae
400


In [31]:
class book:
    def __init__(self, name):
        self.name=name
        p1=book(name="cherry")
        print(p1.name)

In [32]:
class book:
    def __init__(self,name,price,author, page):
        self.name=name
        self.price=price
        self.author=author
        self.page=page
book1=book(name="pythn",price=202,author="pata nae", page=400)
print(book1.name)
print(book1.price)
print(book1.author)
print(book1.page)
    

pythn
202
pata nae
400


In [33]:
class account():
    def __init__(self, owner, balance):
        self.malik = owner
        self.paisa = balance

In [34]:
per_1 = account(owner =" khan", balance = 300)
per_1.malik

' khan'

In [35]:
per_2 = account(owner ="ali ",balance = 400)
per_2.paisa

400

In [36]:
class Rectangle():
    def __init__(self , len , wid):
        self.length = len
        self.width = wid
    def area(self):
        return self.length * self.width
    def perimeter(self):
        return (self.length + self.width)*2

In [38]:
a = [1,2,3]
b = [4,5,6]
c = a[0]+b[2]
print(c)

7


In [39]:
 import numpy as np
list_1 = [3,4,5,6]
arr_1 = np.array(list_1)
arr_1*2


array([ 6,  8, 10, 12])

In [ ]:
type(arr_1)

In [42]:
import numpy as np
numpy.ndarray

NameError: name 'numpy' is not defined